"""add_post_table

Revision ID: 02526a11ea29
Revises: 4c62ef0c9732
Create Date: 2026-05-17 22:10:19.057284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02526a11ea29'
down_revision: Union[str, None] = '4c62ef0c9732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('difficulty_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('tag', sa.Enum('general', 'suggestion', 'problem', 'praise', name='posttag'), nullable=False),
    sa.Column('encrypted_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_author_id', 'post', ['author_id'], unique=False)
    op.create_index('ix_post_difficulty_id', 'post', ['difficulty_id'], unique=False)
    op.create_index('ix_post_parent_id', 'post', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_parent_id', table_name='post')
    op.drop_index('ix_post_difficulty_id', table_name='post')
    op.drop_index('ix_post_author_id', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
