"""add byte_size to post

Revision ID: 1e3278c8bef5
Revises: 605eb397519c
Create Date: 2026-06-02 15:11:47.587550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e3278c8bef5'
down_revision: Union[str, None] = '605eb397519c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('byte_size', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    # Truthful backfill: encrypted_body is ASCII ciphertext, so character length
    # equals the byte length used for storage accounting.
    op.execute("UPDATE post SET byte_size = length(encrypted_body)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'byte_size')
    # ### end Alembic commands ###
