"""add allow_keep_on_browser to mapset

Revision ID: 3157f9806fec
Revises: 1e3278c8bef5
Create Date: 2026-06-17 20:21:47.266328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3157f9806fec'
down_revision: Union[str, None] = '1e3278c8bef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapset', sa.Column('allow_keep_on_browser', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapset', 'allow_keep_on_browser')
    # ### end Alembic commands ###
