"""make_mapset_title_plaintext

Revision ID: 4c62ef0c9732
Revises: f4c85331476e
Create Date: 2026-05-11 17:21:11.685624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c62ef0c9732'
down_revision: Union[str, None] = 'f4c85331476e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapset', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_column('mapset', 'encrypted_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapset', sa.Column('encrypted_title', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('mapset', 'title')
    # ### end Alembic commands ###
