"""add storage byte_size and difficulty_pin table

Revision ID: 605eb397519c
Revises: 4bb749ca5992
Create Date: 2026-06-02 07:51:01.411879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '605eb397519c'
down_revision: Union[str, None] = '4bb749ca5992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficultypin',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('difficulty_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('encrypted_label', sa.Text(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_difficultypin_difficulty_id', 'difficultypin', ['difficulty_id'], unique=False)
    op.add_column('difficultybaseosuversion', sa.Column('byte_size', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sectionosuversion', sa.Column('byte_size', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    # Truthful backfill: the encrypted_content is ASCII (base64 + GCM), so the
    # character length equals the byte length used for storage accounting.
    op.execute(
        "UPDATE sectionosuversion SET byte_size = length(encrypted_content)"
    )
    op.execute(
        "UPDATE difficultybaseosuversion SET byte_size = length(encrypted_content)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sectionosuversion', 'byte_size')
    op.drop_column('difficultybaseosuversion', 'byte_size')
    op.drop_index('ix_difficultypin_difficulty_id', table_name='difficultypin')
    op.drop_table('difficultypin')
    # ### end Alembic commands ###
