"""add_mapset_resource

Revision ID: b3ebf49fac20
Revises: 6e41537db7ac
Create Date: 2026-05-28 20:32:26.965275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3ebf49fac20'
down_revision: Union[str, None] = '6e41537db7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapsetresource',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('mapset_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('encrypted_name', sa.Text(), nullable=False),
    sa.Column('encrypted_url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mapset_id'], ['mapset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mapsetresource_mapset_id', 'mapsetresource', ['mapset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mapsetresource_mapset_id', table_name='mapsetresource')
    op.drop_table('mapsetresource')
    # ### end Alembic commands ###
