"""FastAPI dependencies: auth, CSRF, and membership checks.

Dependencies are the ONLY place where auth / membership checks live.
Inject them at the router level.
"""

import hashlib
import hmac
import secrets
import time
from typing import Annotated
from uuid import UUID

from fastapi import Depends, Header, HTTPException, Request
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.database import get_db
from app.models import User
from app.services.auth_service import AuthServiceError, decode_access_token

# ------------------------------------------------------------------
# CSRF / OAuth state helpers
# ------------------------------------------------------------------

STATE_TTL_SECONDS = 600  # 10 minutes


def generate_oauth_state() -> str:
    """Return a signed, time-bounded state parameter for OAuth init.

    The token binds the OAuth callback to the originating session.
    Format: ``<random_nonce>:<timestamp>:<hmac>``
    """
    nonce = secrets.token_urlsafe(16)
    timestamp = str(int(time.time()))
    payload = f"{nonce}:{timestamp}"
    sig = hmac.new(
        settings.SECRET_KEY.encode(), payload.encode(), hashlib.sha256
    ).hexdigest()[:32]
    return f"{payload}:{sig}"


def validate_oauth_state(state: str) -> bool:
    """Verify that *state* was generated by :func:`generate_oauth_state`.

    Returns ``True`` if the signature is valid and the token is not expired.
    """
    try:
        nonce, timestamp_str, sig = state.rsplit(":", 2)
        timestamp = int(timestamp_str)
    except ValueError:
        return False

    payload = f"{nonce}:{timestamp_str}"
    expected = hmac.new(
        settings.SECRET_KEY.encode(), payload.encode(), hashlib.sha256
    ).hexdigest()[:32]

    if not secrets.compare_digest(sig, expected):
        return False

    if int(time.time()) - timestamp > STATE_TTL_SECONDS:
        return False

    return True


# ------------------------------------------------------------------
# Request origin / custom-header guards
# ------------------------------------------------------------------

async def require_same_origin(request: Request) -> None:
    """Reject requests whose Origin or Referer header points to a foreign host.

    This is a defense-in-depth check for state-changing endpoints.  It is
    **strict by default**: if neither *Origin* nor *Referer* is present the
    request is rejected.  Use :func:`require_csrf_protection` (which adds the
    custom-header check) as the default for cookie-authenticated routes.

    For bearer-token API routes where clients legitimately strip these
    headers, opt out explicitly and rely on ``Authorization`` instead.
    """
    origin = request.headers.get("origin")
    referer = request.headers.get("referer")

    if origin is None and referer is None:
        raise HTTPException(
            status_code=403,
            detail="Missing Origin or Referer header",
        )

    allowed_origin = settings.FRONTEND_URL.rstrip("/")

    if origin is not None:
        if origin.rstrip("/") != allowed_origin:
            raise HTTPException(status_code=403, detail="Invalid Origin header")
        return

    if referer is not None:
        # Referer is a full URL; check that it starts with the allowed origin
        if not referer.startswith(allowed_origin + "/") and referer != allowed_origin:
            raise HTTPException(status_code=403, detail="Invalid Referer header")
        return


async def require_custom_header(
    x_requested_with: Annotated[str | None, Header()] = None,
) -> None:
    """Reject requests that do not carry ``X-Requested-With``.

    Browsers will not automatically attach custom headers on cross-site
    requests, so this acts as a simple CSRF signal for AJAX/fetch calls.
    """
    if x_requested_with is None:
        raise HTTPException(
            status_code=403,
            detail="Missing X-Requested-With header",
        )


async def require_csrf_protection(
    _same_origin: Annotated[None, Depends(require_same_origin)],
    _custom_header: Annotated[None, Depends(require_custom_header)],
) -> None:
    """Combined CSRF guard for cookie-authenticated, state-changing routes.

    Enforces both :func:`require_same_origin` and :func:`require_custom_header`.
    Inject this as a single dependency on POST/PUT/DELETE endpoints that use
    cookie-based session auth.
    """
    # Both sub-dependencies raise on failure; reaching here means both passed.
    pass


# ------------------------------------------------------------------
# Auth / current-user dependency
# ------------------------------------------------------------------


async def get_current_user(
    request: Request,
    db: Annotated[AsyncSession, Depends(get_db)],
) -> User:
    """Resolve the current user from the JWT access-token cookie.

    Returns the fully-hydrated ``User`` row.  Raises ``401`` if the cookie
    is missing, the token is invalid/expired, or the user no longer exists.
    """
    token = request.cookies.get(settings.cookie_name)
    if not token:
        raise HTTPException(status_code=401, detail="Not authenticated")

    try:
        payload = decode_access_token(token)
    except AuthServiceError as exc:
        raise HTTPException(status_code=401, detail=str(exc)) from exc

    sub = payload.get("sub")
    if not sub:
        raise HTTPException(status_code=401, detail="Invalid token payload")
    try:
        user_id = UUID(sub)
    except (ValueError, TypeError):
        raise HTTPException(status_code=401, detail="Invalid token payload")

    user = await db.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=401, detail="User not found")

    return user
